### ISSUE TITLE
[List Playlist with Song][No playlists shown]

### ISSUE THREAD

**Issue by Fdr3iZzz** [huhridge/huh-spicetify-extensions#53]
**Describe the bug**
When I try to see in which playlists the selected song is, I get to see in how many this song appears, but there is no playlist shown specifically.

**To Reproduce**
1 Lissten to a song
2 click on its name -> open it in its album
3 Use the extention to look up the playlists
4 bugged screen appears

**Expected behavior**
It should show the playlists where the song is also available

**Console Errors**
```listPlaylistsWithSong.js?time=1686173505018:259 Uncaught (in promise) TypeError: Cannot read properties of null (reading 'childNodes')
    at Item.listPlaylists [as onClick] (listPlaylistsWithSong.js?time=1686173505018:259:17)
vendor~xpui.js:29 NotFoundError: GET request to sp://core-playlist/v1/playlist/spotify%3Aplaylist%3A37i9dQZF1EYkqdzj48dyYq/?responseFormat=protobufJson&start=0&length=0 failed with status code 404
    at l.onSuccess (xpui.js:1:2030353)
    at onSuccess (xpui.js:1:2030167)
onError @ vendor~xpui.js:29
```

**Screenshots**
![Unbe1nannt](https://github.com/huhridge/huh-spicetify-extensions/assets/37617308/7f87431f-6926-4465-bc12-988770796cf1)
![Unbena2nnt](https://github.com/huhridge/huh-spicetify-extensions/assets/37617308/ec649add-2c41-4b62-b3d4-dc481dbde0a4)

**Desktop (please complete the following information):**
 - OS: Windows
 - Spotify Version: 1.2.12.902.g1924b088
 - Spicetify Version: 2.19.0

**Comment by qsek** [comment]
i have the same problem

**Comment by DhruvGandhi85** [comment]
Same problem

**Comment by Lenullol** [comment]
It's been a while that happened to me too. 
At first the playlists were shown but with a big gap so you had to scroll a long time to get all the playlists but now I only have the number of playlists with music but I don't have their names anymore.

I'm a bit sad that this issue is still there .

**Comment by Zinibow** [comment]
Still an issue it seems
