### ISSUE TITLE
[Playlist Intersection][BUG]

### ISSUE THREAD

**Issue by ruizxzx** [huhridge/huh-spicetify-extensions#83]
**Describe the bug**
 can't create playlist from intersection neither common songs or unique ones!! please fixxx i havent found any other tools to do that shit

**To Reproduce**
just try to compare and then try to create a playlist from the intersection on any mode either common or unique

**Expected behavior**
its supposed to make a playlist on comparing two playlist and create common songs or unique ones from the two compared playlist

**Console Errors**
To check the console, run `spicetify enable-devtools` in the terminal, and press <kbd>Ctrl</kbd>/<kbd>Cmd</kbd>+<kbd>Shift</kbd>+<kbd>i</kbd> and check the console.
![image](https://github.com/huhridge/huh-spicetify-extensions/assets/128290052/61f0e59d-b38a-424e-987a-b807c88f1318)

**Screenshots**
![image](https://github.com/huhridge/huh-spicetify-extensions/assets/128290052/01727fc7-5247-4b9a-85ef-6575f1664f75)

**Desktop (please complete the following information):**
 - OS: win 11 pro (insider beta - official)
 - Spotify Version: spotX (Spotify  1.2.24.756 Windows x86)
 - Spicetify Version: 0.9.3

**Additional context** man fix it plsss
nahh

**Comment by thiagonebuloni** [comment]
Hello, I'm having the same issue. 
Here's the console messages:

![image](https://github.com/huhridge/huh-spicetify-extensions/assets/100470956/8bfe44fe-f6fd-4c34-92ed-fb210e8d47fb)
 
``` js
index.html:1 document.domain mutation is ignored because the surrounding agent cluster is origin-keyed.
(anonymous) @ index.html:1
gue1-spclient.spotify.com/remote-config-resolver/v3/configuration:1 
        
        
       Failed to load resource: the server responded with a status of 404 ()
vendor~xpui.js:29 provider:transport resolve error T Object
f @ vendor~xpui.js:29
index.html:1 Uncaught (in promise) T
extension.js:8 Initializing Spicetify Marketplace v0.9.2
extension.js:8 Loaded Marketplace extension
cdn.jsdelivr.net/gh/spicetify/spicetify-themes@master/Default/user.css?time=1704574599238:1 
        
        
       Failed to load resource: the server responded with a status of 403 ()
cdn.jsdelivr.net/gh/Delusoire/spicetify-extensions@main/dist/keyboard-shortcuts.prism.js?time=1704574599245:1 
        
        
       Failed to load resource: the server responded with a status of 404 ()
index.html:1 Refused to execute script from 'https://cdn.jsdelivr.net/gh/Delusoire/spicetify-extensions@main/dist/keyboard-shortcuts.prism.js?time=1704574599245' because its MIME type ('text/plain') is not executable, and strict MIME type checking is enabled.
xpui.js:1 cosmos-connector:  fetchAdForSlot endpoint=%o sp://ads/v1/ads/hpto
vendor~xpui.js:29 NotFoundError: GET request to sp://core-playlist/v1/playlist/spotify%3Aplaylist%3A37i9dQZF1EYkqdzj48dyYq/?responseFormat=protobufJson&start=0&length=0 failed with status code 404
    at l.onSuccess (xpui.js:1:2110942)
    at onSuccess (xpui.js:1:2110756)
onError @ vendor~xpui.js:29
vendor~xpui.js:29 NotFoundError: GET request to sp://core-playlist/v1/playlist/spotify%3Aplaylist%3A37i9dQZF1EYkqdzj48dyYq/?responseFormat=protobufJson&start=0&length=0 failed with status code 404
    at l.onSuccess (xpui.js:1:2110942)
    at onSuccess (xpui.js:1:2110756)
onError @ vendor~xpui.js:29
h @ vendor~xpui.js:29
(anonymous) @ vendor~xpui.js:29
Promise.catch (async)
l @ vendor~xpui.js:29
(anonymous) @ vendor~xpui.js:29
Promise.then (async)
(anonymous) @ vendor~xpui.js:29
Promise.catch (async)
l @ vendor~xpui.js:29
(anonymous) @ vendor~xpui.js:29
Promise.then (async)
(anonymous) @ vendor~xpui.js:29
playlistIntersection.js?time=1704574599248:574 Uncaught (in promise) TypeError: Cannot set properties of null (setting 'innerHTML')
    at intersect (playlistIntersection.js?time=1704574599248:574:27)
intersect @ playlistIntersection.js?time=1704574599248:574
await in intersect (async)
(anonymous) @ playlistIntersection.js?time=1704574599248:789
item._element.onclick @ spicetifyWrapper.js:1717
3vendor~xpui.js:29 NotFoundError: GET request to sp://core-playlist/v1/playlist/spotify%3Aplaylist%3A37i9dQZF1EYkqdzj48dyYq/?responseFormat=protobufJson&start=0&length=0 failed with status code 404
    at l.onSuccess (xpui.js:1:2110942)
    at onSuccess (xpui.js:1:2110756)
onError @ vendor~xpui.js:29
h @ vendor~xpui.js:29
(anonymous) @ vendor~xpui.js:29
Promise.catch (async)
l @ vendor~xpui.js:29
(anonymous) @ vendor~xpui.js:29
Promise.then (async)
(anonymous) @ vendor~xpui.js:29
Promise.catch (async)
l @ vendor~xpui.js:29
(anonymous) @ vendor~xpui.js:29
Promise.then (async)
(anonymous) @ vendor~xpui.js:29
Promise.catch (async)
l @ vendor~xpui.js:29
(anonymous) @ vendor~xpui.js:29
Promise.then (async)
(anonymous) @ vendor~xpui.js:29
Promise.catch (async)
l @ vendor~xpui.js:29
u @ vendor~xpui.js:29
t.fetch @ vendor~xpui.js:29
n.executeFetch @ vendor~xpui.js:29
n.fetch @ vendor~xpui.js:29
n.refetch @ vendor~xpui.js:29
t.onFocus @ vendor~xpui.js:29
(anonymous) @ vendor~xpui.js:29
(anonymous) @ vendor~xpui.js:29
t.batch @ vendor~xpui.js:29
n.onFocus @ vendor~xpui.js:29
(anonymous) @ vendor~xpui.js:29
(anonymous) @ vendor~xpui.js:29
n.onFocus @ vendor~xpui.js:29
(anonymous) @ vendor~xpui.js:29
n @ vendor~xpui.js:29
xpui.js:1 Uncaught TypeError: Cannot read properties of undefined (reading 'after')
    at Object.current (xpui.js:1:1576627)
    at p.n (xpui.js:1:2222099)
    at p._dispatchFromStore (vendor~xpui.js:29:367023)
    at Array.<anonymous> (vendor~xpui.js:29:368331)
    at a (vendor~xpui.js:29:365564)
    at t (vendor~xpui.js:29:366022)
(anonymous) @ xpui.js:1
n @ xpui.js:1
_dispatchFromStore @ vendor~xpui.js:29
(anonymous) @ vendor~xpui.js:29
a @ vendor~xpui.js:29
t @ vendor~xpui.js:29
postMessage (async)
c @ vendor~xpui.js:29
emit @ vendor~xpui.js:29
emit @ xpui.js:1
emitCreatePlaylistComplete @ xpui.js:1
createPlaylist @ xpui.js:1
convertToPlaylist @ playlistIntersection.js?time=1704574599248:745
onClick @ playlistIntersection.js?time=1704574599248:529
Me @ vendor~xpui.js:29
He @ vendor~xpui.js:29
(anonymous) @ vendor~xpui.js:29
Ui @ vendor~xpui.js:29
Vi @ vendor~xpui.js:29
(anonymous) @ vendor~xpui.js:29
ul @ vendor~xpui.js:29
Re @ vendor~xpui.js:29
Wi @ vendor~xpui.js:29
zt @ vendor~xpui.js:29
Yt @ vendor~xpui.js:29
playlistIntersection.js?time=1704574599248:746 Uncaught (in promise) TypeError: Cannot read properties of null (reading 'split')
    at convertToPlaylist (playlistIntersection.js?time=1704574599248:746:19)
convertToPlaylist @ playlistIntersection.js?time=1704574599248:746
await in convertToPlaylist (async)
onClick @ playlistIntersection.js?time=1704574599248:529
Me @ vendor~xpui.js:29
He @ vendor~xpui.js:29
(anonymous) @ vendor~xpui.js:29
Ui @ vendor~xpui.js:29
Vi @ vendor~xpui.js:29
(anonymous) @ vendor~xpui.js:29
ul @ vendor~xpui.js:29
Re @ vendor~xpui.js:29
Wi @ vendor~xpui.js:29
zt @ vendor~xpui.js:29
Yt @ vendor~xpui.js:29
3vendor~xpui.js:29 NotFoundError: GET request to sp://core-playlist/v1/playlist/spotify%3Aplaylist%3A37i9dQZF1EYkqdzj48dyYq/?responseFormat=protobufJson&start=0&length=0 failed with status code 404
    at l.onSuccess (xpui.js:1:2110942)
    at onSuccess (xpui.js:1:2110756)
```

**Comment by sergifs** [comment]
Hello, I'm having the same issue. If you need any details, please let me know.

**Comment by Darkkal44** [comment]
Any updates on this? Would love to have it fixed!! Was such a dope feature
