### ISSUE TITLE
[skipStats.js] Does Not Work On My Playlists

### ISSUE THREAD

**Issue by eeriemyxi** [huhridge/huh-spicetify-extensions#90]
**The bug**
`skipStats.js` fails to work on my playlists. It errors on the dev-tools console tab.

**To Reproduce**
- install the plugin
- skip some songs from any playlist
- click profile icon > skipStats > See Skips ...
- it won't send any toast messages and will not open any new tab or window

**Console Errors**
```js
Uncaught (in promise) TypeError: Argument `uri` must be a string.
    at se.le [as fromString] (vendor~xpui.js:1:1745300)
    at skipStats.js?time=1711911433372:309:38
    at onClick (spicetifyWrapper.js:1657:57)
    at onClick (spicetifyWrapper.js:1480:7)
    at xpui.js:1:108682
    at Object.Me (vendor~xpui.js:1:2253579)
    at He (vendor~xpui.js:1:2253733)
    at vendor~xpui.js:1:2273615
    at Ui (vendor~xpui.js:1:2273709)
    at Vi (vendor~xpui.js:1:2274123)
    at vendor~xpui.js:1:2279561
    at ul (vendor~xpui.js:1:2342932)
    at Pe (vendor~xpui.js:1:2252712)
    at Wi (vendor~xpui.js:1:2275415)
    at zt (vendor~xpui.js:1:2259826)
    at Yt (vendor~xpui.js:1:2259610)
    at HTMLDivElement.i (vendor~xpui.js:1:175668)
le @ vendor~xpui.js:1
(anonymous) @ skipStats.js?time=1711911433372:309
onClick @ spicetifyWrapper.js:1657
onClick @ spicetifyWrapper.js:1480
(anonymous) @ xpui.js:1
Me @ vendor~xpui.js:1
He @ vendor~xpui.js:1
(anonymous) @ vendor~xpui.js:1
Ui @ vendor~xpui.js:1
Vi @ vendor~xpui.js:1
(anonymous) @ vendor~xpui.js:1
ul @ vendor~xpui.js:1
Pe @ vendor~xpui.js:1
Wi @ vendor~xpui.js:1
zt @ vendor~xpui.js:1
Yt @ vendor~xpui.js:1
i @ vendor~xpui.js:1
```

**Desktop:**
 - OS: `Linux myxi 6.5.0-26-generic #26~22.04.1-Ubuntu SMP PREEMPT_DYNAMIC Tue Mar 12 10:22:43 UTC 2 x86_64 x86_64 x86_64 GNU/Linux`
 - Spotify Version: `Spotify version 1.2.31.1205.g4d59ad7c, Copyright (c) 2024, Spotify Ltd`
 - Spicetify Version: `spicetify v2.32.1`

**Comment by eeriemyxi** [comment]
Let me know if I can help further to debug the issue. I kind of need this plugin.

**Comment by THEKILERFRIEND** [comment]
send your playlist rq

**Comment by eeriemyxi** [comment]
> send your playlist if still got an issue

Hi, I am no longer experiencing this issue with other playlists but one: it does not work on "Liked Songs" playlist that Spotify creates for each user.

![image](https://github.com/huhridge/huh-spicetify-extensions/assets/86738916/a47cf0fc-8e4d-4483-b998-c90aa0b99cfa)

**Comment by THEKILERFRIEND** [comment]
https://github.com/huhridge/huh-spicetify-extensions/issues/95
check if this fixes it for u!

**Comment by eeriemyxi** [comment]
> #95 check if this fixes it for u!

I don't think I have a podcast in there as the track list of my playlist is numbered rather than them all having a musical note as the number.
![image](https://github.com/huhridge/huh-spicetify-extensions/assets/86738916/ffb3174d-7f05-4a74-85b0-b06aedc9c875)
Besides, I have never listened to a podcast using Spotify.
